name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show context
        shell: bash
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "My secret is ${{ secrets.MY_SECRET }}"
          echo "Current branch is '${{ github.ref }}'."

      - name: List files
        shell: bash
        run: tree
